# -*- coding: utf-8 -*-
"""actually reasonable title ig 107+ 108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iMzHT3dypG0A1wxJVzhs-PVXQdi6UKcv
"""

from google.colab import files 
data = files.upload()

import csv 
import pandas as pd 
import plotly.express as px 

df = pd.read_csv("data.csv")

fig = px.bar(df, x="level", y="attempt")
fig.show()

print(df.groupby("level")["attempt"].mean())

from google.colab import files
data = files.upload()

import csv
import pandas as pd
import plotly.figure_factory as ff 

df = pd.read_csv("dihydrogenmonoxide.csv")
fig=ff.create_distplot([df["Mobile Brand"].tolist()], ["Avg Rating"],show_hist=False) 
#i'm not sure why the above line isn't executing, but i submitted this anyway. 
fig.show()