# -*- coding: utf-8 -*-
"""reeeeeeeeee

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H8RccJCXpmgwlU-iOo6-UP01PVyaVkMF
"""

from google.colab import files
data=files.upload()

import csv 
import statistics
import pandas as pd

df=pd.read_csv("StudentsPerformance.csv")
reading=df["# reading score"].to_list() #am not sure why this isn't working
reading_mean = statistics.mean(reading)
reading_median = statistics.median(reading)
reading_mode = statistics.mode(reading)
std_deviation=statistics.stdev(reading)

first_std_dev_start, first_std_dev_end = reading_mean - std_deviation, reading_mean + std_deviation
list_of_data_within_1_std_deviation = [result for result in reading if result > first_std_dev_start and result < first_std_dev_end]
print("{}% of data lies within 1 std dev", format(len(list_of_data_within_1_std_deviation)*100/len(reading)))

second_std_dev_start, second_std_dev_end = reading_mean - std_deviation, reading_mean + std_deviation
list_of_data_within_2_std_deviation = [result for result in reading if result > second_std_dev_start and result < second_std_dev_end]
print("{}% of data lies within 2 std dev", format(len(list_of_data_within_2_std_deviation)*100/len(reading)))

third_std_dev_start, third_std_dev_end = reading_mean - std_deviation, reading_mean + std_deviation
list_of_data_within_3_std_deviation = [result for result in reading if result > third_std_dev_start and result < third_std_dev_end]
print("{}% of data lies within 3 std dev", format(len(list_of_data_within_3_std_deviation)*100/len(reading)))